# Generated by Django 5.0 on 2023-12-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
