version: "3.8"

services:
    mysqldb:
        container_name: mysqldb
        image: mysql:8
        env_file:
            - ./.env.db
        volumes:
            - mysqldata:/var/lib/mysql
            - ./mysqldata/seed.sql:/docker-entrypoint-initdb.d/seed.sql
        restart: always

    web:
        container_name: djangoapi
        build:
            context: .
        env_file:
            - ./.env
        volumes:
            - static_volume_store:/app/static/
            - media_volume_store:/app/media/
        depends_on:
            - mysqldb
        restart: always

    nginx:
        container_name: nginx
        build: ./nginx
        volumes:
            - static_volume_store:/app/static/
            - media_volume_store:/app/media/
        ports:
            - 80:80
        restart: always
        depends_on:
            - web

volumes:
    mysqldata:
    static_volume_store:
    media_volume_store:
